/**
 * BLACK - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       BLACK (retail original Xbox)
 *   Title ID:    0x45410083
 *   Base addr:   0x00010000
 *   Entry point: 0x00025A3F
 *   Code size:   2,125,740 bytes (.text)
 *   Sections:    13
 *   Kernel imports: 115
 */

#include <windows.h>
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>
#include "recomp_icall_feedback.h"

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x00025A3F  /* XBE entry point VA */
#define YOUR_GAME_XBE_PATH      "game\\default.xbe"
#define YOUR_GAME_DIR            "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* Native keyboard/mouse: how a keyboard action finds the control the live action map gives it
 * (recomp_manual.c, BLACK_PC_INPUT). */
extern int black_pc_input_resolver(int slot);
extern void pc_input_set_control_resolver(int (*resolver)(int slot));
extern int black_pc_input_gameplay_blocked_query(void);
extern void pc_input_set_gameplay_blocked_query(int (*query)(void));

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host RIP and nothing else -- there is no guest program counter to
 * report, and the host address changes every build. Two things recover the
 * guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the linker's PDB already maps host address back to guest
 *     function. dbghelp turns an anonymous RIP into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires linking dbghelp and keeping the .pdb beside the .exe.
 */
static void print_guest_context(void *rip)
{
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
    }
}

/* The emulated APU.
 *
 * Two entry points that had no callers anywhere in the tree. apu_mmio_hook.c
 * documents apu_hook_handle_mmio as "called from VEH in main.c" and no main.c
 * called it; apu_decode_and_handle's first line is `if (!g_apu_state) return
 * false` and nothing assigned g_apu_state. So with RECOMP_AC97_READY set the
 * APU's registers were unmapped to be trapped, and every trap was then
 * declined and surfaced as an access violation on the first register
 * DirectSound touched.
 *
 * Declared rather than included so this does not depend on src/apu being on
 * the include path. */
typedef struct MCPXAPUState MCPXAPUState;
extern MCPXAPUState *mcpx_apu_init_standalone(uint8_t *ram_ptr);
extern void mcpx_apu_dump_state(void);
extern void xbox_AddHangReport(void (*report)(void));
extern unsigned long mcpx_apu_frame_thread_id(void);
extern void xbox_AddHangThread(unsigned long tid, const char *name);
extern MCPXAPUState *g_apu_state;
extern void mcpx_apu_irq_service_begin(void *opaque);
extern void mcpx_apu_irq_service_end(void *opaque);
extern bool apu_hook_handle_mmio(PCONTEXT ctx, uintptr_t fault_addr,
                                 uint32_t fault_xbox_va, int is_write);

/* The APU's interrupt line, as the kernel delivers it. */
static void apu_irq_line(int asserted)
{
    xbox_SetInterruptLine(XBOX_APU_VECTOR, asserted);
}

/* The trapped span, matching what MemoryLayoutInit unmaps: the APU's own
 * 512 KB, not the whole MCPX aperture. AC'97 above it stays plain memory,
 * which is what the codec-ready bit needs. */
#define APU_TRAP_BASE 0xFE800000u
#define APU_TRAP_END  0xFE880000u

/* Guest memory the crash report may read without faulting again: main RAM
 * and the contiguous window, both mapped by xbox_MemoryLayoutInit. A second
 * fault inside the handler would recurse, so anything else is skipped. */
static int guest_readable(uint32_t va, uint32_t bytes)
{
    if (va >= 0x00010000u && va + bytes <= 0x04000000u && va + bytes > va)
        return 1;
    if (va >= 0x80000000u && va + bytes <= 0x84000000u && va + bytes > va)
        return 1;
    return 0;
}

static void dump_guest_words(const char *label, uint32_t va, int count)
{
    const uint32_t *p;
    int i;

    if (!g_xbox_mem_offset || !guest_readable(va, (uint32_t)count * 4u))
        return;
    p = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + va);
    fprintf(stderr, "  %s 0x%08X:", label, va);
    for (i = 0; i < count; i++) {
        if (i % 8 == 0)
            fprintf(stderr, "\n    +%02X:", i * 4);
        fprintf(stderr, " %08X", p[i]);
    }
    fprintf(stderr, "\n");
}

/* Raw guest stack and the objects it points at.
 *
 * Only eax/ecx/edx/esp are global; ebx/esi/edi/ebp live in the generated
 * function's locals, so the register line cannot say what a crashing function
 * was working on. Its arguments are on the guest stack, though, and one level
 * of pointers from there is usually the object whose state is wrong.
 * RECOMP_CRASH_PEEK=va,va,... dumps further addresses found that way on the
 * next run (the layout is deterministic from boot). */
static void dump_guest_crash_memory(void)
{
    const uint32_t *sp;
    int i, shown = 0;

    if (!g_xbox_mem_offset || !guest_readable(g_esp, 32 * 4))
        return;
    dump_guest_words("guest stack", g_esp, 32);
    sp = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
    for (i = 0; i < 32 && shown < 12; i++) {
        uint32_t v = sp[i];
        char label[32];
        if (v > g_xbox_code_lo && v < g_xbox_code_hi)
            continue;                       /* return address, not an object */
        if (!guest_readable(v, 0x60))
            continue;
        snprintf(label, sizeof(label), "[esp+%02X] ->", i * 4);
        dump_guest_words(label, v, 24);
        shown++;
    }
    {
        const char *spec = getenv("RECOMP_CRASH_PEEK");
        char buf[256], *tok, *ctx = NULL;
        if (spec) {
            strncpy(buf, spec, sizeof(buf) - 1);
            buf[sizeof(buf) - 1] = 0;
            for (tok = strtok_s(buf, ",", &ctx); tok;
                 tok = strtok_s(NULL, ",", &ctx))
                dump_guest_words("peek", (uint32_t)strtoul(tok, NULL, 0), 24);
        }
    }
}

/* RECOMP_FPE_TRAP=1 (lab diagnostic): the main thread runs with the invalid-operation exception unmasked (re-armed once a
 * frame); the first few distinct places that make a NaN or compare one are printed, then the exception is masked again and
 * the instruction runs on. Finds where a NaN is made. */
static __declspec(thread) int s_fpe_stepping;
static LONG CALLBACK fpe_veh(PEXCEPTION_POINTERS ep)
{
    static struct { uint64_t rip; long count; } seen[64];
    static int nseen;
    static volatile LONG total;
    int i;
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_SINGLE_STEP && s_fpe_stepping) {
        /* the instruction that trapped has run masked: arm the trap again */
        ep->ContextRecord->EFlags &= ~0x100u;
        ep->ContextRecord->MxCsr &= ~0x80u;
        s_fpe_stepping = 0;
        return EXCEPTION_CONTINUE_EXECUTION;
    }
    if (ep->ExceptionRecord->ExceptionCode != EXCEPTION_FLT_INVALID_OPERATION) return EXCEPTION_CONTINUE_SEARCH;
    InterlockedIncrement(&total);
    for (i = 0; i < nseen && seen[i].rip != ep->ContextRecord->Rip; i++) {}
    if (i == nseen && nseen < 64) {
        seen[nseen].rip = ep->ContextRecord->Rip; seen[nseen].count = 0; nseen++;
        fprintf(stderr, "[FPE] #%d invalid operation at RIP=0x%llX (total so far %ld)\n", i, (unsigned long long)ep->ContextRecord->Rip, (long)total);
        fprintf(stderr, "  RIP = black_xbox_recomp.exe+0x%llX\n",
                (unsigned long long)(ep->ContextRecord->Rip - (uintptr_t)GetModuleHandleA(NULL)));
        {
            IMAGEHLP_LINE64 line;
            DWORD ldisp = 0;
            memset(&line, 0, sizeof(line));
            line.SizeOfStruct = sizeof(line);
            if (SymGetLineFromAddr64(GetCurrentProcess(), (DWORD64)ep->ContextRecord->Rip, &ldisp, &line))
                fprintf(stderr, "  at %s:%lu\n", line.FileName, (unsigned long)line.LineNumber);
        }
        print_guest_context((void *)ep->ContextRecord->Rip);
        fflush(stderr);
    }
    if (i < nseen) {
        long c = ++seen[i].count;
        if (c == 100 || c == 10000 || c == 1000000)
            fprintf(stderr, "[FPE] #%d at RIP=0x%llX: %ld hits\n", i, (unsigned long long)ep->ContextRecord->Rip, c);
    }
    ep->ContextRecord->MxCsr |= 0x80;
    ep->ContextRecord->EFlags |= 0x100u;      /* single-step the instruction, then unmask again */
    s_fpe_stepping = 1;
    return EXCEPTION_CONTINUE_EXECUTION;
}

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        /* APU registers -> the emulated APU.
         *
         * The other half of RECOMP_AC97_READY: reporting the codec ready is
         * what lets DirectSoundCreate past its first gate, and from there it
         * drives the APU directly, so the registers have to fault to be seen.
         * "Handled" means the access was decoded and the instruction stepped
         * over, so execution resumes instead of unwinding. */
        {
            uint32_t xbox_va =
                (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);

            if (xbox_va >= APU_TRAP_BASE && xbox_va < APU_TRAP_END
                    && apu_hook_handle_mmio(
                           ep->ContextRecord, fault_addr, xbox_va,
                           ep->ExceptionRecord->ExceptionInformation[0]
                               ? 1 : 0)) {
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        /* Image-relative RIP survives ASLR, so it can be looked up in the
         * PDB or a map file after the fact. */
        fprintf(stderr, "  RIP = black_xbox_recomp.exe+0x%llX\n",
            (unsigned long long)(ep->ContextRecord->Rip -
                                 (uintptr_t)GetModuleHandleA(NULL)));
        fprintf(stderr, "  PC regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  PC regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  PC VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));
        print_guest_context((void *)ep->ContextRecord->Rip);
        dump_guest_crash_memory();

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    } else {
        /* Other faults that end the process (a divide by zero in generated code, say): name where, as for a bad access. */
        DWORD code = ep->ExceptionRecord->ExceptionCode;
        if (code == EXCEPTION_INT_DIVIDE_BY_ZERO || code == EXCEPTION_INT_OVERFLOW ||
            code == EXCEPTION_ILLEGAL_INSTRUCTION || code == EXCEPTION_PRIV_INSTRUCTION) {
            fprintf(stderr, "[CRASH] exception 0x%08lX at RIP=0x%llX\n", (unsigned long)code,
                    (unsigned long long)ep->ContextRecord->Rip);
            fprintf(stderr, "  RIP = black_xbox_recomp.exe+0x%llX\n",
                    (unsigned long long)(ep->ContextRecord->Rip - (uintptr_t)GetModuleHandleA(NULL)));
            fprintf(stderr, "  PC regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n", g_eax, g_ecx, g_edx, g_esp);
            fprintf(stderr, "  native regs: rax=%llX rcx=%llX rdx=%llX rbx=%llX rsi=%llX rdi=%llX\n",
                    (unsigned long long)ep->ContextRecord->Rax, (unsigned long long)ep->ContextRecord->Rcx,
                    (unsigned long long)ep->ContextRecord->Rdx, (unsigned long long)ep->ContextRecord->Rbx,
                    (unsigned long long)ep->ContextRecord->Rsi, (unsigned long long)ep->ContextRecord->Rdi);
            print_guest_context((void *)ep->ContextRecord->Rip);
            fflush(stderr);
        }
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
    RECOMP_ICALL_FEEDBACK_INIT();

    printf("=== BLACK - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);
    if (getenv("RECOMP_FPE_TRAP")) AddVectoredExceptionHandler(1, fpe_veh);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing PC memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize PC memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("PC memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Bring up the emulated APU.
     *
     * Gated on the same variable that unmaps its registers, because the two
     * halves are useless apart: a trap with no model declines every access,
     * and a model nothing traps into never sees a register. The APU walks
     * Xbox physical RAM to find voice buffers, notifiers and sample data,
     * so it gets physical address 0 as the title's MmGetPhysicalAddress
     * sees it: the contiguous window. Given the guest RAM base it read the
     * low guest addresses, which are separate storage, so DirectSound's
     * voice links, samples and notifiers never reached it or came back. */
    if (getenv("RECOMP_AC97_READY")) {
        g_apu_state = mcpx_apu_init_standalone(
            (uint8_t *)xbox_GetPhysicalMemoryBase());
        /* Its interrupt goes to the kernel's APU vector, where DirectSound
         * connects the ISR that completes stream packets. */
        if (g_apu_state) {
            /* Register before the title can activate or connect the APU ISR.
             * The APU stays alive until process exit; if explicit retirement
             * is added, stop kernel delivery before removing this guard. */
            xbox_SetInterruptServiceGuard(XBOX_APU_VECTOR,
                                          mcpx_apu_irq_service_begin,
                                          mcpx_apu_irq_service_end, g_apu_state);
            mcpx_apu_set_irq_line(apu_irq_line);
            xbox_AddHangReport(mcpx_apu_dump_state);
            xbox_AddHangThread(mcpx_apu_frame_thread_id(), "APU frame");
        }
        fprintf(stderr, "[BOOT] emulated APU %s\n",
                g_apu_state ? "up" : "FAILED to initialise");
    }

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing PC kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, "save");
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    /* Before the guest reads its first pad report: keyboard actions resolve through the live map. */
    pc_input_set_control_resolver(black_pc_input_resolver);
    pc_input_set_gameplay_blocked_query(black_pc_input_gameplay_blocked_query);

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
